apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:CR75WgluTHjhRsa6chcdP36J3nEH1cFrrWtHXNW2SFY="
  APP_DEBUG: "true"
  APP_LOG_LEVEL: "debug"
  APP_URL: "http://localhost"

  DB_CONNECTION: "mysql"
  DB_HOST: "database"
  DB_PORT: "3306"
  DB_DATABASE: "homestead"
  DB_USERNAME: "homestead"
  DB_PASSWORD: "secret"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"
  QUEUE_DRIVER: "sync"

  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: "6379"

  MAIL_DRIVER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"